apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podkrepibg

bases:
  - ../../base

patches:
  - path: manual/keycloak-config.patch.yaml
  - path: manual/deployment.patch.yaml
  - path: manual/sendgrid-config.patch.yaml

images:
  - name: ghcr.io/podkrepi-bg/api
    newTag: master
  - name: ghcr.io/podkrepi-bg/api/migrations
    newTag: master
