---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-headless
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-headless
  template:
    spec:
      initContainers:
        - name: migrate-database
          imagePullPolicy: IfNotPresent
      containers:
        - name: api-headless
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_ENV
              value: production
            - name: APP_URL
              value: https://podkrepi.bg/
            - name: IRIS_API_URL
              value: https://developer.irispay.bg/api/8
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-access
                  key: Endpoint
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-access
                  key: AccessKey
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-access
                  key: SecretKey
            - name: BANK_TRANSACTION_FILES_BUCKET
              value: banktransaction-files
            - name: CAMPAIGN_APPLICATIONS_FILES_BUCKET
              value: campaignapplication-files
            - name: CAMPAIGN_FILES_BUCKET
              value: campaign-files-prod
            - name: CAMPAIGN_NEWS_FILES_BUCKET
              value: campaign-news-files
            - name: EXPENSES_FILES_BUCKET
              value: expenses-files
            - name: IRREGULARITY_FILES_BUCKET
              value: irregularity-files
