---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-headless
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-headless
  template:
    spec:
      initContainers:
        - name: migrate-database
          imagePullPolicy: IfNotPresent
      containers:
        - name: api-headless
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_ENV
              value: production
            - name: APP_URL
              value: https://podkrepi.bg/
            - name: IRIS_API_URL
              value: https://developer.irispay.bg/api/8
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-object-user-object-store-object-store-admin
                  key: Endpoint
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-object-user-object-store-object-store-admin
                  key: AccessKey
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-object-user-object-store-object-store-admin
                  key: SecretKey
