name: 'Test Report'
on:
  workflow_run:
    workflows: ['API tests'] # runs after API tests workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results # artifact name
          name: JEST Tests # Name of the check run which will be created
          path: 'test-results.xml' # Path to test results (inside artifact .zip)
          reporter: jest-junit # Format of test results
